using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using GADE7322_POE.UI;

// GameManager
// -----------
// This script manages the main game loop, initializes the terrain and tower, handles wave spawning,
// tracks resources, and manages game state (start, pause, game over).
// Attach this script to an empty GameObject in your scene (e.g., GameManager).

public class GameManager : MonoBehaviour
{
    // -----------------------------
    // CONFIGURABLE FIELDS
    // -----------------------------

    [Header("References")]
    [Tooltip("Reference to the VoxelTerrainGenerator in the scene.")]
    public VoxelTerrainGenerator terrainGenerator;
    [Tooltip("Tower prefab to instantiate at the center.")]
    public GameObject towerPrefab;
    [Tooltip("Default enemy prefab to spawn.")]
    public GameObject defaultEnemyPrefab;
    [Tooltip("Fast enemy prefab to spawn.")]
    public GameObject fastEnemyPrefab;
    [Tooltip("Tank enemy prefab to spawn.")]
    public GameObject tankEnemyPrefab;
    [Tooltip("Time (seconds) between enemy spawns in a wave.")]
    public float enemySpawnInterval = 2f;
    [Tooltip("Number of enemies in the first wave.")]
    public int initialWaveEnemyCount = 5;
    [Tooltip("Factor by which enemy count increases per wave.")]
    public float waveScalingFactor = 1.5f;
    [Tooltip("Factor by which enemy health increases per wave.")]
    public float healthScalingFactor = 1.2f;
    [Tooltip("Factor by which enemy speed increases per wave.")]
    public float speedScalingFactor = 1.1f;

    [Header("Defenders & Resources")]
    [Tooltip("Defender prefab to place on valid terrain.")]
    public GameObject defenderPrefab;
    [Tooltip("Resource cost to place a defender.")]
    public int defenderCost = 25;
    [Tooltip("Resources the player starts with.")]
    public int startingResources = 100;

    [Header("Placement Offsets")]
    [Tooltip("Y-offset for tower placement (half height if pivot at center)")]
    public float towerYOffset = 1f;
    [Tooltip("Y-offset for enemy spawning (half height if pivot at center)")]
    public float enemyYOffset = 1f;
    [Tooltip("Y-offset for defender placement (half height if pivot at center)")]
    public float defenderYOffset = 1f;

    [Header("Placement Offsets")]
    [Tooltip("Y-offset for tower placement (half height if pivot at center)")]
    public float towerOffset = 2f;
    [Tooltip("Y-offset for enemy spawning (half height if pivot at center)")]
    public float enemyOffset = 2f;
    [Tooltip("Y-offset for defender placement (half height if pivot at center)")]
    public float defenderOffset = 2f;

    // UI References
    public HealthBarUI towerHealthBar;
    public ResourceCounterUI resourceCounterUI;
    public DefenderCostUI defenderCostUI;
    public GameOverUI gameOverUI;
    public PauseMenuUI pauseMenuUI;

    // -----------------------------
    // GAME STATE VARIABLES
    // -----------------------------

    private GameObject towerInstance;
    public GameObject TowerInstance { get { return towerInstance; } }
    public int currentWave = 1;
    private int resources = 0;
    private bool isGameOver = false;
    private bool isPaused = false;
    private EnemySpawner enemySpawner;
    public Tower tower { get; private set; }

    // -----------------------------
    // UNITY LIFECYCLE
    // -----------------------------

    void Start()
    {
        // Hide UI panels that should be hidden at start
        if (gameOverUI != null)
            gameOverUI.Hide();
        if (pauseMenuUI != null)
            pauseMenuUI.Hide();

        // Step 1: Initialize the terrain (should already be generated by VoxelTerrainGenerator)
        if (terrainGenerator == null)
        {
            Debug.LogError("GameManager: No VoxelTerrainGenerator assigned!");
            return;
        }

        // Initialize resources and UI
        resources = Mathf.Max(0, startingResources);
        if (resourceCounterUI != null)
            resourceCounterUI.SetResource(resources);
        if (defenderCostUI != null)
            defenderCostUI.SetCost(defenderCost);

        // Step 2: Spawn the tower at the center of the terrain (ensure terrain is ready)
        if (!terrainGenerator.IsReady)
        {
            // Force generation if needed
            terrainGenerator.GetCenterGrid();
        }
        SpawnTower();

    // Step 3: Initialize EnemySpawner
        enemySpawner = GetComponent<EnemySpawner>();
        if (enemySpawner == null)
        {
            enemySpawner = gameObject.AddComponent<EnemySpawner>();
        }
        enemySpawner.gameManager = this;
        enemySpawner.defaultEnemyPrefab = defaultEnemyPrefab;
        enemySpawner.fastEnemyPrefab = fastEnemyPrefab;
        enemySpawner.tankEnemyPrefab = tankEnemyPrefab;
        enemySpawner.spawnInterval = enemySpawnInterval;
        enemySpawner.initialWaveEnemyCount = initialWaveEnemyCount;
        enemySpawner.waveScalingFactor = waveScalingFactor;
        enemySpawner.healthScalingFactor = healthScalingFactor;
        enemySpawner.speedScalingFactor = speedScalingFactor;
    }

    void Update()
    {
        // Handle pause input (using new Input System)
        if (UnityEngine.InputSystem.Keyboard.current != null && UnityEngine.InputSystem.Keyboard.current[UnityEngine.InputSystem.Key.Escape].wasPressedThisFrame)
        {
            TogglePause();
        }
    }

    // -----------------------------
    // TOWER SPAWNING
    // -----------------------------

    void SpawnTower()
    {
        Vector3Int center = terrainGenerator.GetCenterGrid();
        Vector3 towerPos = terrainGenerator.GetSurfaceWorldPosition(center);
        towerPos.y += towerYOffset;
        towerInstance = Instantiate(towerPrefab, towerPos, Quaternion.identity);
    }

    // -----------------------------
    // ENEMY WAVE SPAWNING
    // -----------------------------

    IEnumerator SpawnWave(int enemyCount)
    {
        // For each path, spawn enemies at the entrance
        for (int i = 0; i < enemyCount; i++)
        {
            SpawnEnemyOnRandomPath();
            yield return new WaitForSeconds(enemySpawnInterval);
        }
        // After wave, you could start next wave or wait for player input
    }

    void SpawnEnemyOnRandomPath()
    {
        // Pick a random path entrance from the terrain generator
        if (terrainGenerator == null || terrainGenerator.numPaths == 0)
            return;
        System.Collections.Generic.List<System.Collections.Generic.List<UnityEngine.Vector3Int>> paths = terrainGenerator.GetPaths();
        if (paths == null || paths.Count == 0) return;
        int pathIndex = Random.Range(0, paths.Count);
        System.Collections.Generic.List<UnityEngine.Vector3Int> path = paths[pathIndex];
        if (path == null || path.Count == 0) return;
        UnityEngine.Vector3Int entrance = path[0];
        Vector3 spawnPos = terrainGenerator.GetSurfaceWorldPosition(entrance);
        spawnPos.y += enemyYOffset;
        GameObject enemyObj = Instantiate(defaultEnemyPrefab, spawnPos, Quaternion.identity);
        Enemy enemy = enemyObj.GetComponent<Enemy>();
        if (enemy != null)
        {
            Tower towerComponent = towerInstance != null ? towerInstance.GetComponent<Tower>() : null;
            enemy.Initialize(path, terrainGenerator.height, towerComponent, this);
        }
    }

    // -----------------------------
    // RESOURCE MANAGEMENT
    // -----------------------------

    public void AddResources(int amount)
    {
        resources += amount;
        if (resourceCounterUI != null)
            resourceCounterUI.SetResource(resources);
    }

    public bool SpendResources(int amount)
    {
        if (resources >= amount)
        {
            resources -= amount;
            if (resourceCounterUI != null)
                resourceCounterUI.SetResource(resources);
            return true;
        }
        return false;
    }

    public int GetResources()
    {
        return resources;
    }

    // -----------------------------
    // GAME STATE MANAGEMENT
    // -----------------------------

    public void GameOver()
    {
        isGameOver = true;
        // Show game over UI, stop spawning, etc.
        if (gameOverUI != null)
            gameOverUI.Show("Game Over!");
        Debug.Log("Game Over!");
    }

    public bool IsGameOver()
    {
        return isGameOver;
    }

    // -----------------------------
    // PAUSE & RESTART (OPTIONAL)
    // -----------------------------

    public void TogglePause()
    {
        if (isPaused)
        {
            ResumeGame();
        }
        else
        {
            PauseGame();
        }
    }

    public void PauseGame()
    {
        isPaused = true;
        Time.timeScale = 0f;
        if (pauseMenuUI != null)
            pauseMenuUI.Show();
    }

    public void ResumeGame()
    {
        isPaused = false;
        Time.timeScale = 1f;
        if (pauseMenuUI != null)
            pauseMenuUI.Hide();
    }

    public void RestartGame()
    {
        // Resume time scale before restarting
        Time.timeScale = 1f;
        // Reload the current scene
        UnityEngine.SceneManagement.SceneManager.LoadScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene().name);
    }

    public bool IsPaused()
    {
        return isPaused;
    }

    // Call this when the tower takes damage or is healed:
    // if (towerHealthBar != null) towerHealthBar.SetHealth(currentHealth, maxHealth);

    // Call this when the defender cost changes:
    // if (defenderCostUI != null) defenderCostUI.SetCost(defenderCost);

    // -----------------------------
    // DEFENDER PLACEMENT API
    // -----------------------------

    public bool TryPlaceDefender(Vector3Int gridPosition)
    {
        if (isGameOver || isPaused) return false;
        if (defenderPrefab == null || terrainGenerator == null) return false;

        // Only allow placement on valid non-path tiles
        if (!terrainGenerator.IsValidDefenderPlacement(gridPosition)) return false;

        if (!SpendResources(defenderCost)) return false;

        // Clamp to terrain bounds to avoid OOB
        int gx = Mathf.Clamp(gridPosition.x, 0, terrainGenerator.width - 1);
        int gz = Mathf.Clamp(gridPosition.z, 0, terrainGenerator.depth - 1);
        Vector3 worldPos = terrainGenerator.GetSurfaceWorldPosition(new Vector3Int(gx, 0, gz));
        worldPos.y += defenderYOffset;
        Instantiate(defenderPrefab, worldPos, Quaternion.identity);
        return true;
    }
} 